-- Daily Cost Report (Run via SnowSQL)
USE ROLE ACCOUNTADMIN;
SELECT 
    WAREHOUSE_NAME, 
    SUM(CREDITS_USED) AS TOTAL_CREDITS,
    AVG(CREDITS_USED) AS AVG_CREDITS
FROM ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY 
WHERE DATE(START_TIME) = CURRENT_DATE() 
GROUP BY 1 
ORDER BY 2 DESC;
