-- ETL Pipeline: Snowpipe + Task + Stream
CREATE OR REPLACE STAGE STAGING_DB.PUBLIC.MY_STAGE;
CREATE OR REPLACE PIPE SALES_PIPE AUTO_INGEST=TRUE AS
    COPY INTO SALES FROM @MY_STAGE/sales.csv
    FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1);

CREATE OR REPLACE TASK DAILY_LOAD
    WAREHOUSE = DEV_WH
    SCHEDULE = 'USING CRON 0 6 * * * Europe/London'
AS
    ALTER PIPE SALES_PIPE REFRESH;

CREATE OR REPLACE STREAM SALES_STREAM ON TABLE SALES;

-- Start Task
ALTER TASK DAILY_LOAD RESUME;
