-- RBAC Setup for UK Team
USE ROLE SECURITYADMIN;

CREATE OR REPLACE ROLE DBA_KUMAR;
CREATE OR REPLACE USER KUMAR PASSWORD='SecurePass2025!' DEFAULT_ROLE=DBA_KUMAR;
GRANT ROLE DBA_KUMAR TO USER KUMAR;

CREATE OR REPLACE ROLE ANALYST_UK;
GRANT USAGE ON DATABASE PROD_DB TO ROLE ANALYST_UK;
GRANT USAGE ON SCHEMA PROD_DB.SALES TO ROLE ANALYST_UK;
GRANT SELECT ON ALL TABLES IN SCHEMA PROD_DB.SALES TO ROLE ANALYST_UK;
