-- Security Audit: Recent Failed Logins
SELECT 
    USER_NAME, 
    EVENT_TIMESTAMP, 
    ERROR_MESSAGE,
    CLIENT_IP
FROM ACCOUNT_USAGE.LOGIN_HISTORY
WHERE IS_SUCCESS = 'NO' 
  AND EVENT_TIMESTAMP > DATEADD(HOUR, -24, CURRENT_TIMESTAMP())
ORDER BY EVENT_TIMESTAMP DESC;
